const mongoose = require("mongoose");
const db = require("../models");

// This file empties the tasks and user collection and inserts info below

// NOTE:
// This user and tasks seed is NO good since User is linked with Task
// using user._id generated by mongo + passport instead of name

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/atomicmuffin"
);

const tasksSeed = [
  {
    user: "hey@email.com",
    name: "go to the beach",
    isComplete: false,
    dateCreated: new Date(2019, 4, 12),
    dateDue: new Date(2019, 4, 12),
  },
  {
    user: "hey@email.com",
    name: "eat ice cream",
    isComplete: false,
    dateCreated: new Date(2019, 4, 13),
    dateDue: new Date(2019, 4, 13),
  },
  {
    user: "hey@email.com",
    name: "eat avocado",
    isComplete: false,
    dateCreated: new Date(2019, 4, 14),
    dateDue: new Date(2019, 4, 14),
  },
  {
    user: "hey@email.com",
    name: "drink more water",
    isComplete: false,
    dateCreated: new Date(2019, 4, 14),
    dateDue: new Date(2019, 4, 14),
  },
  {
    user: "hi@email.com",
    name: "swim at the lake",
    isComplete: false,
    dateCreated: new Date(2019, 4, 15),
    dateDue: new Date(2019, 4, 15),
  },
  {
    user: "hi@email.com",
    name: "drink coffee",
    isComplete: false,
    dateCreated: new Date(2019, 4, 15),
    dateDue: new Date(2019, 4, 15),
  }
];

db.Task
  .deleteMany({})
  .then(() => db.Task.collection.insertMany(tasksSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });


  const userSeed = [
    {
      name: "user 1",
      email: "user1@email.com",
      password: "pass1",
    },
    {
      name: "user 2",
      email: "user2@email.com",
      password: "pass2",
    }
  ];


db.User
.deleteMany({})
.then(() => db.User.collection.insertMany(userSeed))
.then(data => {
  console.log(data.result.n + " records inserted!");
  process.exit(0);
})
.catch(err => {
  console.error(err);
  process.exit(1);
});
